version: "3"

services: 
  web:
    container_name: simple-api-rest
    restart: always
    build: .
    ports: 
      - "3000:3000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  mongo:
    container_name: mongodb
    image: mongo
    ports: 
      - "27018:27017"